version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - image="sagemaker-tf-frauddet-example"
      - chmod +x frauddet/train
      - chmod +x frauddet/serve
      - account=$(aws sts get-caller-identity --query Account --output text)
      - region="us-east-1"
      - fullname="${account}.dkr.ecr.${region}.amazonaws.com/${image}:latest"
      - $(aws ecr get-login --region ${region} --no-include-email)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build  -t ${image} .
      - docker tag ${image} ${fullname}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${fullname}
