version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - image="sagemaker-tf-frauddet-example"
      - chmod +x frauddet/train
      - chmod +x frauddet/serve
      - account=$(aws sts get-caller-identity --query Account --output text)
      - region=$(aws configure get region)
      - region=${region:-us-west-2}
      - fullname="${account}.dkr.ecr.${region}.amazonaws.com/${algorithm_name}:latest"
      - aws ecr describe-repositories --repository-names "${image}" > /dev/null 2>&1
      - $(aws ecr get-login --region ${region} --no-include-email)

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build  -t ${image} .
      - docker tag ${image} ${fullname}
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push ${fullname}
